blank_issues_enabled: true
contact_links:
  - name: QTY Core Security Policy
    url: https://github.com/qty/qty/blob/master/SECURITY.md
    about: View security policy
  - name: QTY Core Developers
    url: https://qtycore.org
    about: QTY Core homepage
