.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. qty_qt test_qty_qt
clean: FORCE
	$(MAKE) -C .. qty_qt_clean test_qty_qt_clean
check: FORCE
	$(MAKE) -C .. test_qty_qt_check
qty-qt qty-qt.exe: FORCE
	 $(MAKE) -C .. qty_qt
apk: FORCE
	$(MAKE) -C .. qty_qt_apk
