dist_man1_MANS=

if BUILD_QTYD
  dist_man1_MANS+=qtyd.1
endif

if ENABLE_QT
  dist_man1_MANS+=qty-qt.1
endif

if BUILD_QTY_CLI
  dist_man1_MANS+=qty-cli.1
endif

if BUILD_QTY_TX
  dist_man1_MANS+=qty-tx.1
endif

if BUILD_QTY_UTIL
  dist_man1_MANS+=qty-util.1
endif

if ENABLE_WALLET
if BUILD_QTY_WALLET
  dist_man1_MANS+=qty-wallet.1
endif
endif
