#!/usr/bin/env bash
#
#  qtyd The qty core server.
#
#
# chkconfig: 345 80 20
# description: qtyd
# processname: qtyd
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/qtyd, see below
if [ -f /etc/sysconfig/qtyd ]; then
        . /etc/sysconfig/qtyd
fi

RETVAL=0

prog=qtyd
# you can override the lockfile via QTYD_LOCKFILE in /etc/sysconfig/qtyd
lockfile=${QTYD_LOCKFILE-/var/lock/subsys/qtyd}

# qtyd defaults to /usr/bin/qtyd, override with QTYD_BIN
qtyd=${QTYD_BIN-/usr/bin/qtyd}

# qtyd opts default to -disablewallet, override with QTYD_OPTS
qtyd_opts=${QTYD_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $qtyd $qtyd_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
